-- ─────────────────────────────────────────────────────────────────
-- 잠사박물관 BLE 비콘 근태 시스템 — Supabase 스키마 확장
-- 적용일: 2026-05-19
--
-- 전제: 기존에 staff, attendance 테이블이 존재해야 함.
--       없을 경우 본 파일 상단의 CREATE TABLE IF NOT EXISTS 블록이
--       최소 스키마를 만들어 줌.
-- ─────────────────────────────────────────────────────────────────

-- ── 0. 최소 스키마 보장 (이미 있다면 무시) ───────────────────────
create table if not exists public.staff (
  id            bigint generated by default as identity primary key,
  name          text not null,
  created_at    timestamptz not null default now()
);

create table if not exists public.attendance (
  id            bigint generated by default as identity primary key,
  staff_id      bigint references public.staff(id) on delete cascade,
  checked_in_at timestamptz not null default now(),
  checked_out_at timestamptz,
  created_at    timestamptz not null default now()
);

-- ── 1. staff 컬럼 확장 ───────────────────────────────────────────
alter table public.staff
  add column if not exists beacon_namespace text,
  add column if not exists beacon_instance  text,
  add column if not exists beacon_mac       text,
  add column if not exists dept_code        smallint,
  add column if not exists contract_type    text,            -- 정규직/계약직/시급제/외주
  add column if not exists visa_type        text,            -- E-9 / H-2 / F-4 등
  add column if not exists visa_expires_at  date,
  add column if not exists insurance_status text,            -- 가입/미가입/만료
  add column if not exists country          text,
  add column if not exists phone            text,
  add column if not exists hire_date        date;

-- beacon_instance는 1인 1비콘 → UNIQUE
do $$
begin
  if not exists (
    select 1 from pg_indexes
    where schemaname = 'public'
      and indexname  = 'staff_beacon_instance_key'
  ) then
    create unique index staff_beacon_instance_key
      on public.staff (beacon_instance)
      where beacon_instance is not null;
  end if;
end$$;

create index if not exists staff_dept_code_idx on public.staff (dept_code);

-- dept_code CHECK (1~255, 0x01~0xFF)
alter table public.staff
  drop constraint if exists staff_dept_code_chk;
alter table public.staff
  add constraint staff_dept_code_chk
  check (dept_code is null or (dept_code between 1 and 255));

-- contract_type CHECK
alter table public.staff
  drop constraint if exists staff_contract_type_chk;
alter table public.staff
  add constraint staff_contract_type_chk
  check (contract_type is null or contract_type in ('정규직','계약직','시급제','외주'));

-- ── 2. attendance 컬럼 확장 ─────────────────────────────────────
alter table public.attendance
  add column if not exists raw_rssi             integer,
  add column if not exists estimated_distance_m numeric(6,2),
  add column if not exists beacon_mac           text,
  add column if not exists beacon_namespace     text,
  add column if not exists beacon_instance      text,
  add column if not exists gateway_id           text,
  add column if not exists dept_code            smallint;   -- denormalized for RLS 빠른 필터

create index if not exists attendance_staff_idx     on public.attendance (staff_id);
create index if not exists attendance_dept_idx      on public.attendance (dept_code);
create index if not exists attendance_checked_in_idx on public.attendance (checked_in_at desc);

-- ── 3. 부서 마스터 (UI/뱃지용 — 선택) ───────────────────────────
create table if not exists public.beacon_dept (
  code   smallint primary key,
  name   text not null,
  color  text,
  note   text
);

insert into public.beacon_dept (code, name, color, note) values
  (1, '관리부',          'emerald', '예: 0x01'),
  (2, '시설부',          'blue',    '예: 0x02'),
  (3, '외국인 노동자',   'orange',  '예: 0x03 — E-9/H-2 비자')
on conflict (code) do update
  set name = excluded.name,
      color = excluded.color,
      note  = excluded.note;

-- 0x04~0xFF 예비 코드는 운영자가 UI에서 추가

-- ── 4. attendance 입력 시 dept_code 자동 채움 트리거 ────────────
create or replace function public.attendance_fill_dept()
returns trigger language plpgsql as $$
begin
  if new.dept_code is null and new.staff_id is not null then
    select s.dept_code into new.dept_code
      from public.staff s
     where s.id = new.staff_id;
  end if;
  return new;
end$$;

drop trigger if exists trg_attendance_fill_dept on public.attendance;
create trigger trg_attendance_fill_dept
  before insert or update on public.attendance
  for each row execute function public.attendance_fill_dept();

-- ── 5. 로그인 사용자 → dept_code 매핑 (JWT custom claim 또는 staff 테이블) ─
-- 권장: auth.users.id == staff.auth_uid 컬럼으로 1:1 매칭
alter table public.staff
  add column if not exists auth_uid uuid;

create unique index if not exists staff_auth_uid_key
  on public.staff (auth_uid) where auth_uid is not null;

create or replace function public.current_staff_dept_code()
returns smallint language sql stable security definer as $$
  select dept_code from public.staff
   where auth_uid = auth.uid()
   limit 1;
$$;

create or replace function public.current_user_is_admin_dept()
returns boolean language sql stable security definer as $$
  -- 관리부(dept_code=1) 또는 supabase service_role
  select coalesce(public.current_staff_dept_code() = 1, false)
      or coalesce((auth.jwt() ->> 'role') = 'service_role', false);
$$;

-- ── 6. RLS 활성화 ───────────────────────────────────────────────
alter table public.staff       enable row level security;
alter table public.attendance  enable row level security;
alter table public.beacon_dept enable row level security;

-- beacon_dept: 모두 조회 가능, 변경은 관리부만
drop policy if exists beacon_dept_read on public.beacon_dept;
create policy beacon_dept_read on public.beacon_dept
  for select using (true);

drop policy if exists beacon_dept_write on public.beacon_dept;
create policy beacon_dept_write on public.beacon_dept
  for all using (public.current_user_is_admin_dept())
            with check (public.current_user_is_admin_dept());

-- ── 7. staff RLS ────────────────────────────────────────────────
-- 관리부: 전체 조회/수정 가능
-- 일반 부서: 본인 + 본인 부서 동료만 조회 (외국인=3 은 제외)
-- 외국인 노동자(3): 본인 정보만 조회

drop policy if exists staff_select on public.staff;
create policy staff_select on public.staff
  for select using (
    public.current_user_is_admin_dept()
    or auth_uid = auth.uid()
    or (
      dept_code = public.current_staff_dept_code()
      and dept_code <> 3
    )
  );

drop policy if exists staff_insert on public.staff;
create policy staff_insert on public.staff
  for insert with check (public.current_user_is_admin_dept());

drop policy if exists staff_update on public.staff;
create policy staff_update on public.staff
  for update using (public.current_user_is_admin_dept())
              with check (public.current_user_is_admin_dept());

drop policy if exists staff_delete on public.staff;
create policy staff_delete on public.staff
  for delete using (public.current_user_is_admin_dept());

-- ── 8. attendance RLS ───────────────────────────────────────────
-- 외국인(dept_code=3) 출근 기록은 관리부만 조회 가능.
-- 일반 부서: 자기 부서만.
-- 본인: 본인 기록.

drop policy if exists attendance_select on public.attendance;
create policy attendance_select on public.attendance
  for select using (
    public.current_user_is_admin_dept()
    or (
      dept_code <> 3
      and dept_code = public.current_staff_dept_code()
    )
    or staff_id in (
      select id from public.staff where auth_uid = auth.uid()
    )
  );

-- INSERT: 비콘 게이트웨이는 service_role 키로 푸시 → 자동 통과
-- 일반 사용자: 본인 기록만 수동 입력 허용
drop policy if exists attendance_insert on public.attendance;
create policy attendance_insert on public.attendance
  for insert with check (
    public.current_user_is_admin_dept()
    or staff_id in (
      select id from public.staff where auth_uid = auth.uid()
    )
  );

drop policy if exists attendance_update on public.attendance;
create policy attendance_update on public.attendance
  for update using (public.current_user_is_admin_dept())
              with check (public.current_user_is_admin_dept());

drop policy if exists attendance_delete on public.attendance;
create policy attendance_delete on public.attendance
  for delete using (public.current_user_is_admin_dept());

-- ── 9. 편의 뷰 — UI에서 자주 사용 ────────────────────────────────
create or replace view public.v_attendance_today as
  select a.*,
         s.name              as staff_name,
         s.beacon_instance,
         s.contract_type,
         s.visa_type,
         s.visa_expires_at,
         s.country,
         d.name              as dept_name,
         d.color             as dept_color
    from public.attendance a
    left join public.staff       s on s.id   = a.staff_id
    left join public.beacon_dept d on d.code = coalesce(a.dept_code, s.dept_code)
   where a.checked_in_at::date = current_date
   order by a.checked_in_at desc;

create or replace view public.v_foreign_workers as
  select s.*,
         d.name  as dept_name,
         d.color as dept_color,
         case
           when s.visa_expires_at is null                          then 'unknown'
           when s.visa_expires_at <  current_date                   then 'expired'
           when s.visa_expires_at <  current_date + interval '30 day' then 'warning'
           when s.visa_expires_at <  current_date + interval '90 day' then 'soon'
           else 'ok'
         end as visa_status
    from public.staff s
    left join public.beacon_dept d on d.code = s.dept_code
   where s.dept_code = 3;

-- ── 끝 ──────────────────────────────────────────────────────────
