-- ═══════════════════════════════════════════════════════════════════
-- 잠사박물관 BLE 비콘 HR — ALL-IN-ONE 설치 스크립트
-- 적용일: 2026-05-20
--
-- 이 파일 하나만 SQL Editor 에 붙여넣고 Run 하면 끝.
-- 기존 데이터/테이블/뷰가 어떤 상태든 안전 (모두 IF NOT EXISTS / IF EXISTS 사용).
-- 중복 실행해도 데이터 손실 없음.
-- ═══════════════════════════════════════════════════════════════════

-- ── 1. 테이블 생성 ──────────────────────────────────────────────
create table if not exists public.staff (
  id         bigint generated by default as identity primary key,
  name       text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.attendance (
  id              bigint generated by default as identity primary key,
  staff_id        bigint references public.staff(id) on delete cascade,
  checked_in_at   timestamptz not null default now(),
  checked_out_at  timestamptz,
  created_at      timestamptz not null default now()
);

create table if not exists public.beacon_dept (
  code   smallint primary key,
  name   text not null,
  color  text,
  note   text
);

-- ── 2. staff 컬럼 확장 ──────────────────────────────────────────
alter table public.staff
  add column if not exists beacon_namespace text,
  add column if not exists beacon_instance  text,
  add column if not exists beacon_mac       text,
  add column if not exists dept_code        smallint,
  add column if not exists contract_type    text,
  add column if not exists visa_type        text,
  add column if not exists visa_expires_at  date,
  add column if not exists insurance_status text,
  add column if not exists country          text,
  add column if not exists phone            text,
  add column if not exists hire_date        date,
  add column if not exists auth_uid         uuid;

-- ── 3. attendance 컬럼 확장 ─────────────────────────────────────
alter table public.attendance
  add column if not exists raw_rssi             integer,
  add column if not exists estimated_distance_m numeric(6,2),
  add column if not exists beacon_mac           text,
  add column if not exists beacon_namespace     text,
  add column if not exists beacon_instance      text,
  add column if not exists gateway_id           text,
  add column if not exists dept_code            smallint,
  add column if not exists last_seen_at         timestamptz,
  add column if not exists auto_closed          boolean default false,
  add column if not exists close_reason         text;

-- ── 4. 인덱스 (멱등) ─────────────────────────────────────────────
do $$
begin
  if not exists (select 1 from pg_indexes where schemaname='public' and indexname='staff_beacon_instance_key') then
    create unique index staff_beacon_instance_key on public.staff (beacon_instance) where beacon_instance is not null;
  end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and indexname='staff_auth_uid_key') then
    create unique index staff_auth_uid_key on public.staff (auth_uid) where auth_uid is not null;
  end if;
end$$;

create index if not exists staff_dept_code_idx          on public.staff (dept_code);
create index if not exists attendance_staff_idx         on public.attendance (staff_id);
create index if not exists attendance_dept_idx          on public.attendance (dept_code);
create index if not exists attendance_checked_in_idx    on public.attendance (checked_in_at desc);

-- open attendance 인덱스
create index if not exists attendance_open_idx
  on public.attendance (staff_id, checked_in_at)
  where checked_out_at is null;

-- ── 5. CHECK 제약 ───────────────────────────────────────────────
alter table public.staff drop constraint if exists staff_dept_code_chk;
alter table public.staff add  constraint staff_dept_code_chk
  check (dept_code is null or (dept_code between 1 and 255));

alter table public.staff drop constraint if exists staff_contract_type_chk;
alter table public.staff add  constraint staff_contract_type_chk
  check (contract_type is null or contract_type in ('정규직','계약직','시급제','외주'));

-- ── 6. 부서 마스터 데이터 ────────────────────────────────────────
insert into public.beacon_dept (code, name, color, note) values
  (1, '관리부',          'emerald', '예: 0x01'),
  (2, '시설부',          'blue',    '예: 0x02'),
  (3, '외국인 노동자',   'orange',  '예: 0x03 — E-9/H-2 비자')
on conflict (code) do update set name=excluded.name, color=excluded.color, note=excluded.note;

-- ── 7. 트리거 함수: attendance.dept_code 자동 채움 ───────────────
create or replace function public.attendance_fill_dept()
returns trigger language plpgsql as $$
begin
  if new.dept_code is null and new.staff_id is not null then
    select s.dept_code into new.dept_code from public.staff s where s.id = new.staff_id;
  end if;
  return new;
end$$;

drop trigger if exists trg_attendance_fill_dept on public.attendance;
create trigger trg_attendance_fill_dept
  before insert or update on public.attendance
  for each row execute function public.attendance_fill_dept();

-- ── 8. 헬퍼 함수 ────────────────────────────────────────────────
create or replace function public.current_staff_dept_code()
returns smallint language sql stable security definer as $$
  select dept_code from public.staff where auth_uid = auth.uid() limit 1;
$$;

create or replace function public.current_user_is_admin_dept()
returns boolean language sql stable security definer as $$
  select coalesce(public.current_staff_dept_code() = 1, false)
      or coalesce((auth.jwt() ->> 'role') = 'service_role', false);
$$;

-- ── 9. RLS 활성화 + 정책 ────────────────────────────────────────
alter table public.staff       enable row level security;
alter table public.attendance  enable row level security;
alter table public.beacon_dept enable row level security;

-- beacon_dept
drop policy if exists beacon_dept_read  on public.beacon_dept;
create policy beacon_dept_read  on public.beacon_dept for select using (true);
drop policy if exists beacon_dept_write on public.beacon_dept;
create policy beacon_dept_write on public.beacon_dept for all
  using (public.current_user_is_admin_dept()) with check (public.current_user_is_admin_dept());

-- staff
drop policy if exists staff_select on public.staff;
create policy staff_select on public.staff for select using (
  public.current_user_is_admin_dept()
  or auth_uid = auth.uid()
  or (dept_code = public.current_staff_dept_code() and dept_code <> 3)
);
drop policy if exists staff_insert on public.staff;
create policy staff_insert on public.staff for insert with check (public.current_user_is_admin_dept());
drop policy if exists staff_update on public.staff;
create policy staff_update on public.staff for update
  using (public.current_user_is_admin_dept()) with check (public.current_user_is_admin_dept());
drop policy if exists staff_delete on public.staff;
create policy staff_delete on public.staff for delete using (public.current_user_is_admin_dept());

-- attendance
drop policy if exists attendance_select on public.attendance;
create policy attendance_select on public.attendance for select using (
  public.current_user_is_admin_dept()
  or (dept_code <> 3 and dept_code = public.current_staff_dept_code())
  or staff_id in (select id from public.staff where auth_uid = auth.uid())
);
drop policy if exists attendance_insert on public.attendance;
create policy attendance_insert on public.attendance for insert with check (
  public.current_user_is_admin_dept()
  or staff_id in (select id from public.staff where auth_uid = auth.uid())
);
drop policy if exists attendance_update on public.attendance;
create policy attendance_update on public.attendance for update
  using (public.current_user_is_admin_dept()) with check (public.current_user_is_admin_dept());
drop policy if exists attendance_delete on public.attendance;
create policy attendance_delete on public.attendance for delete using (public.current_user_is_admin_dept());

-- ── 10. 뷰 (DROP + CREATE — 컬럼 중복 절대 방지) ───────────────
drop view if exists public.v_attendance_today cascade;
create view public.v_attendance_today as
  select a.id,
         a.staff_id,
         a.checked_in_at,
         a.checked_out_at,
         a.raw_rssi,
         a.estimated_distance_m,
         a.beacon_mac          as att_beacon_mac,
         a.beacon_namespace    as att_beacon_namespace,
         a.beacon_instance     as att_beacon_instance,
         a.gateway_id,
         a.dept_code           as att_dept_code,
         s.name                as staff_name,
         s.dept_code           as staff_dept_code,
         s.beacon_instance     as staff_beacon_instance,
         s.contract_type       as staff_contract_type,
         s.visa_type           as staff_visa_type,
         s.visa_expires_at     as staff_visa_expires_at,
         s.country             as staff_country,
         d.name                as dept_name,
         d.color               as dept_color
    from public.attendance a
    left join public.staff       s on s.id   = a.staff_id
    left join public.beacon_dept d on d.code = coalesce(a.dept_code, s.dept_code)
   where a.checked_in_at::date = current_date
   order by a.checked_in_at desc;

drop view if exists public.v_foreign_workers cascade;
create view public.v_foreign_workers as
  select s.id, s.name, s.dept_code,
         s.beacon_namespace, s.beacon_instance, s.beacon_mac,
         s.contract_type, s.visa_type, s.visa_expires_at,
         s.insurance_status, s.country, s.phone, s.hire_date, s.auth_uid,
         d.name  as dept_name,
         d.color as dept_color,
         case
           when s.visa_expires_at is null                            then 'unknown'
           when s.visa_expires_at <  current_date                     then 'expired'
           when s.visa_expires_at <  current_date + interval '30 day' then 'warning'
           when s.visa_expires_at <  current_date + interval '90 day' then 'soon'
           else 'ok'
         end as visa_status
    from public.staff s
    left join public.beacon_dept d on d.code = s.dept_code
   where s.dept_code = 3;

-- ── 11. Phase 2 — 자동 체크아웃 함수 + 결근 테이블 ──────────────
create or replace function public.auto_close_stale_attendance()
returns integer language plpgsql security definer as $$
declare closed_count integer;
begin
  update public.attendance
     set checked_out_at = coalesce(last_seen_at, checked_in_at),
         auto_closed    = true,
         close_reason   = 'auto-timeout'
   where checked_out_at is null
     and coalesce(last_seen_at, checked_in_at) < now() - interval '5 minutes';
  get diagnostics closed_count = row_count;
  return closed_count;
end$$;

create table if not exists public.absence_records (
  id         bigint generated by default as identity primary key,
  staff_id   bigint not null references public.staff(id) on delete cascade,
  date       date not null,
  type       text not null check (type in ('absent','late','early_leave','sick','vacation','public_holiday')),
  minutes    integer,
  note       text,
  created_at timestamptz not null default now(),
  unique (staff_id, date, type)
);

create index if not exists absence_records_date_idx on public.absence_records (date desc);

alter table public.absence_records enable row level security;
drop policy if exists absence_select on public.absence_records;
create policy absence_select on public.absence_records for select using (
  public.current_user_is_admin_dept()
  or staff_id in (select id from public.staff where auth_uid = auth.uid())
);
drop policy if exists absence_write on public.absence_records;
create policy absence_write on public.absence_records for all
  using (public.current_user_is_admin_dept()) with check (public.current_user_is_admin_dept());

-- ── 12. Phase 2 — 근무시간 뷰 ──────────────────────────────────
drop view if exists public.v_work_hours cascade;
create view public.v_work_hours as
with closed as (
  select a.*,
         coalesce(a.checked_out_at, now()) as out_at,
         extract(epoch from (coalesce(a.checked_out_at, now()) - a.checked_in_at)) / 60.0 as minutes_total
    from public.attendance a
   where a.checked_in_at is not null
)
select c.id, c.staff_id, c.dept_code, c.checked_in_at, c.out_at,
       round(c.minutes_total::numeric, 1)                as minutes_total,
       round((c.minutes_total / 60.0)::numeric, 2)       as hours_total,
       case
         when extract(hour from c.checked_in_at) >= 22 or extract(hour from c.out_at) < 6
         then round((c.minutes_total * 1.5 / 60.0)::numeric, 2)
         else round((c.minutes_total / 60.0)::numeric, 2)
       end                                                as hours_paid_est,
       case when extract(dow from c.checked_in_at) = 0 then true else false end as is_holiday,
       c.auto_closed, c.close_reason
  from closed c;

drop view if exists public.v_daily_summary cascade;
create view public.v_daily_summary as
select s.id              as staff_id,
       s.name            as staff_name,
       s.dept_code,
       d.name            as dept_name,
       a.checked_in_at::date as work_date,
       min(a.checked_in_at)  as first_in,
       max(a.out_at)         as last_out,
       round(sum(a.minutes_total)::numeric / 60.0, 2) as total_hours,
       count(*) filter (where a.auto_closed) as auto_closed_sessions
  from public.staff s
  left join public.beacon_dept d on d.code = s.dept_code
  left join public.v_work_hours a on a.staff_id = s.id
 group by s.id, s.name, s.dept_code, d.name, a.checked_in_at::date;

-- ═══════════════════════════════════════════════════════════════════
-- 설치 확인 — 정상이면 8줄 모두 OK 가 보임
-- ═══════════════════════════════════════════════════════════════════
select 'staff'              as object, 'table' as kind, count(*)::text as rows from public.staff           union all
select 'attendance'         as object, 'table' as kind, count(*)::text as rows from public.attendance      union all
select 'beacon_dept'        as object, 'table' as kind, count(*)::text as rows from public.beacon_dept     union all
select 'absence_records'    as object, 'table' as kind, count(*)::text as rows from public.absence_records union all
select 'v_attendance_today' as object, 'view'  as kind, count(*)::text as rows from public.v_attendance_today union all
select 'v_foreign_workers'  as object, 'view'  as kind, count(*)::text as rows from public.v_foreign_workers  union all
select 'v_work_hours'       as object, 'view'  as kind, count(*)::text as rows from public.v_work_hours    union all
select 'v_daily_summary'    as object, 'view'  as kind, count(*)::text as rows from public.v_daily_summary;
