-- ─────────────────────────────────────────────────────────────────
-- Phase 2 — 출퇴근 자동화 (자동 체크아웃 + 근무시간 계산)
-- 적용일: 2026-06-20 (예정)
-- 전제: 20260519_beacon_attendance.sql 이미 적용
-- ─────────────────────────────────────────────────────────────────

-- ── 1. attendance 자동 체크아웃 컬럼 ────────────────────────────
alter table public.attendance
  add column if not exists last_seen_at timestamptz,
  add column if not exists auto_closed  boolean default false,
  add column if not exists close_reason text;   -- 'auto-timeout' / 'manual' / 'override'

create index if not exists attendance_open_idx
  on public.attendance (staff_id, checked_in_at)
  where checked_out_at is null;

-- ── 2. 매분 실행할 자동 체크아웃 함수 ───────────────────────────
-- 5분 이상 last_seen_at 갱신 없는 open attendance → 자동 종료
create or replace function public.auto_close_stale_attendance()
returns integer language plpgsql security definer as $$
declare
  closed_count integer;
begin
  update public.attendance
     set checked_out_at = coalesce(last_seen_at, checked_in_at),
         auto_closed    = true,
         close_reason   = 'auto-timeout'
   where checked_out_at is null
     and coalesce(last_seen_at, checked_in_at) < now() - interval '5 minutes';
  get diagnostics closed_count = row_count;
  return closed_count;
end$$;

-- pg_cron 사용 가능 시 (Supabase Pro+):
-- select cron.schedule('auto-checkout', '* * * * *',
--   $$ select public.auto_close_stale_attendance(); $$);
-- (무료 플랜은 minew-server 의 워커가 1분마다 RPC 호출)

-- ── 3. 결근/지각/조퇴 기록 테이블 ───────────────────────────────
create table if not exists public.absence_records (
  id            bigint generated by default as identity primary key,
  staff_id      bigint not null references public.staff(id) on delete cascade,
  date          date not null,
  type          text not null check (type in ('absent','late','early_leave','sick','vacation','public_holiday')),
  minutes       integer,                          -- 지각/조퇴 분 수
  note          text,
  created_at    timestamptz not null default now(),
  unique (staff_id, date, type)
);

create index if not exists absence_records_date_idx on public.absence_records (date desc);

-- ── 4. 근무시간 뷰 (한국 근로기준법 가산율 반영) ────────────────
-- 야간 22:00~06:00 = 1.5배 / 휴일(주휴 일요일, 토요일은 0배 가정) = 1.5배
create or replace view public.v_work_hours as
with closed as (
  select a.*,
         coalesce(a.checked_out_at, now()) as out_at,
         extract(epoch from (coalesce(a.checked_out_at, now()) - a.checked_in_at)) / 60.0 as minutes_total
    from public.attendance a
   where a.checked_in_at is not null
)
select c.id, c.staff_id, c.dept_code, c.checked_in_at, c.out_at,
       round(c.minutes_total::numeric, 1)                          as minutes_total,
       round((c.minutes_total / 60.0)::numeric, 2)                 as hours_total,
       -- 야간 가산 추정 (단순화: 22~06 사이가 근무에 포함됐는지)
       case
         when extract(hour from c.checked_in_at) >= 22
           or extract(hour from c.out_at) < 6
         then round((c.minutes_total * 1.5 / 60.0)::numeric, 2)
         else round((c.minutes_total / 60.0)::numeric, 2)
       end                                                          as hours_paid_est,
       -- 일요일 가산
       case when extract(dow from c.checked_in_at) = 0 then true else false end as is_holiday,
       c.auto_closed,
       c.close_reason
  from closed c;

-- ── 5. attendance 갱신 트리거: last_seen_at 자동 갱신 ───────────
create or replace function public.attendance_touch_last_seen()
returns trigger language plpgsql as $$
begin
  -- 동일 staff_id 의 open attendance 가 있으면 last_seen_at 만 업데이트
  if exists (
    select 1 from public.attendance
     where staff_id = new.staff_id
       and checked_out_at is null
  ) then
    update public.attendance
       set last_seen_at = new.checked_in_at
     where staff_id = new.staff_id
       and checked_out_at is null;
    -- 새 row 는 무시 (중복 방지)
    return null;
  end if;
  -- 첫 출근 → 그대로 insert
  return new;
end$$;

drop trigger if exists trg_attendance_touch on public.attendance;
-- BEFORE INSERT — 같은 staff 의 open attendance 있으면 INSERT 취소
create trigger trg_attendance_touch
  before insert on public.attendance
  for each row execute function public.attendance_touch_last_seen();

-- ── 6. RLS — Phase 1 정책 그대로 상속 + 신규 테이블 ────────────
alter table public.absence_records enable row level security;

drop policy if exists absence_select on public.absence_records;
create policy absence_select on public.absence_records
  for select using (
    public.current_user_is_admin_dept()
    or staff_id in (select id from public.staff where auth_uid = auth.uid())
  );

drop policy if exists absence_write on public.absence_records;
create policy absence_write on public.absence_records
  for all using (public.current_user_is_admin_dept())
            with check (public.current_user_is_admin_dept());

-- ── 7. 일별 요약 뷰 (대시보드용) ────────────────────────────────
create or replace view public.v_daily_summary as
select s.id              as staff_id,
       s.name            as staff_name,
       s.dept_code,
       d.name            as dept_name,
       a.checked_in_at::date as work_date,
       min(a.checked_in_at)  as first_in,
       max(a.out_at)         as last_out,
       round(sum(a.minutes_total)::numeric / 60.0, 2) as total_hours,
       count(*) filter (where a.auto_closed) as auto_closed_sessions
  from public.staff s
  left join public.beacon_dept d on d.code = s.dept_code
  left join public.v_work_hours a on a.staff_id = s.id
 group by s.id, s.name, s.dept_code, d.name, a.checked_in_at::date;

-- ── 끝 ──────────────────────────────────────────────────────────
